# 違反とする文字数を指定します。30と指定した場合、
# 空欄なしの30文字以上の英字を打ち込んだ場合カウント対象になります
ViolateAlphabetLength: 30

# 警告をチャットに表示する回数を指定します。
# 2, 3 とした場合、2回目と3回目の違反の時に警告が出されます。
WarnAmounts: [2, 3]

# キックを行う回数を指定します。
# 5とした場合5回違反したときにキックされます
KickAmount: 5

# 警告メッセージを指定します。&を使用してカラーコードを指定できます。
# <count>は違反回数に置き換わります。
# 例: <count>回違反しました！ -> 3回違反しました！
WarnMessage: "&e<count>回スパムを行っています！ &cおやめください！"

# Kickされたときのメッセージを指定します。
# &を使用してカラーコードを指定できます。
# Warn同様<count>は違反回数に置き換わります。
KickMessage: "&cあなたは<count>回スパムを行ったためKickされました。"

# 処罰対象が半角英数字か英字のみかを指定します
# trueの場合はスペースなしの半角英数字となり、falseの場合はスペースなしの半角英字となります。
IncludeNumber: true

# この機能によってKickされた時に違反回数をリセットするかを設定できます。
# trueの場合はリセットされ、falseの場合はリセットされません。
ResetViolationOnKick: false

# プレイヤーが退出したときにリセットするかどうかを指定します。
# これは/kickコマンドなどによる退出も全て含みます。
# ただし ResetViolationOnKick と設定が衝突した場合は ResetViolationOnKick の方が尊重されます。
# trueでリセット、falseでリセットされません。
ResetViolationOnLeft: true

# 違反チャットだが警告もKickもされていない回数の場合にチャットをキャンセルするかどうか
CancelChatOnNormal: false
# 警告が出された時のチャットをキャンセルするかどうか
CancelChatOnWarn: true
# Kickされた時のチャットをキャンセルするかどうか
CancelChatOnKick: true